Client:
    type: entity
    table: client
    indexes:
        IDX_C7440455D7904E20:
            columns:
                - postaladdressid
        IDX_C744045576B09341:
            columns:
                - billingaddressid
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        lastname:
            type: string
            nullable: true
            length: 30
            options:
                fixed: false
        firstname:
            type: string
            nullable: true
            length: 30
            options:
                fixed: false
        login:
            type: string
            nullable: true
            length: 30
            options:
                fixed: false
        password:
            type: string
            nullable: true
            length: 256
            options:
                fixed: false
        email:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
        gender:
            type: string
            nullable: true
            length: 10
            options:
                fixed: false
        phone:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
    manyToOne:
        postaladdressid:
            targetEntity: Address
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                postaladdressid:
                    referencedColumnName: id
            orphanRemoval: false
        billingaddressid:
            targetEntity: Address
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                billingaddressid:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
